swagger: "2.0"
info:
  version: "0.0.1"
  title: Quick Hit Projects - Independent Development Plan
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /api
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /user:
    x-swagger-router-controller: userController
    post:
      description: Register a new user account
      operationId: registerUser
      parameters:
        - name: user
          in: body
          description: User record to register
          required: true
          schema:
            $ref: "#/definitions/UserRegistrationRequest"
      responses:
        "201":
          description: Success
          schema:
            $ref: "#/definitions/UserRegistrationResponse"
        "422":
          description: Invalid Request Data
          schema:
            $ref: "#/definitions/UserRegistrationResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  UserRegistrationRequest:
    required:
      - username
      - firstName
      - lastName
      - email
      - password
    properties:
      username:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string
        format: password
      manager:
        type: string
      dateOfHire:
        type: string
        format: date
      team:
        type: string
      project:
        type: string
      office:
        type: string
      jobTitle:
        type: string
      phone:
        type: string
  UserRegistrationResponse:
    required:
      - username
      - message
    properties:
      message:
        type: string
      username:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
